Daf/redevance domaniale introduction in OpenFiscaPF
govpf/openfisca-pf pull request #19
Opened 2022-01-18 23:15 UTC by Mael-Congard-SIPF

* Tax and benefit system adaptation for the public domain pricing of French Polynesia 
* Details:
  - New feature for public domain pricing including parameters, variables and tests

- - - -

These changes :
- Add a new feature (for instance adding a variable)

2022-01-24 21:58 UTC, masterbox requested changes
Review done by MB et AD
Have fun !

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        nature_emprise_occupation_redevance_domaniale = where(type_calcul == '1', nature_emprise_occupation_redevance_domaniale.decode_to_str(), 'ip_eco_01_equipement_pays')
why decode to string and why specify something for others types as the final result will be 0

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        montant_total = arrondiSup(montant_intermediaire * (1 - 0.8 * activite_cultuelle))
0.8 should be a parameter

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +    value_type = str
Should be an enum

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +    label = "Montant de annuel de la redevance domaniale sur les lotissements agricoles"
correct label please

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +        zone_lot_agri = personne('zone_lot_agri', period)
why not zone_lot_agricole ???

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +        for item in code_commune.decode():
we should create the method aggregateParameters and add a parameter to decode values

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +    label = "Montant total de la redevance domaniale dûe sur le domùaine privé"
fix label

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        return where(type_calcul == '1', temporalite, 'Not Applicable')
"en français"

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_23.py
> +        duree_occupation_redevance_domaniale = personne('duree_occupation_redevance_domaniale', period)
no need to use unit ?

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_3.py
> +        init = parameters(period).daf.redevance_domaniale.type_3[nature_emprise_occupation_redevance_domaniale].init
Why in english ? as all other parameters are in french :D

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_3.py
> +        init = parameters(period).daf.redevance_domaniale.type_3[nature_emprise_occupation_redevance_domaniale].init
why not use brackets instead ?

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_3.py
> +        activite_cultuelle = personne('activite_cultuelle', period)
typo activite_cultuelle => activite_culturelle

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_8.py
> +    label = "Montant total de la redevance domaniale dûe avec un calcul dépendant de l'archipel'"
typo remove useless '

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_8.py
> +class temporalite_redevance_domaniale_type_8(Variable):
always the same OF variable... Should we add a generic method ?

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +    label = "Montant de base (journalier, annuel, mensuel) de la redevance domaniale sur le domaine privée"
privée => privé

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +        # valeur_venale = parameters(period).daf.redevance_domaniale.commune_prive[code_commune][zone_domaine_prive].valeur_venale
remove if useless

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +        for item in code_commune.decode():
use new aggregateParameters method

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +    label = "Montant total de la redevance domaniale dûe sur le domùaine privé"
domùaine => domaine

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_test.py
> +# -*- coding: utf-8 -*-
remove test file

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/enums_loc.py
> +# -*- coding: utf-8 -*-
rename file to enums_localisations ?

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/enums_loc.py
> +    zone_habitat = u'Zone d habitat'
add \' to have "zone d'habitat"

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Unité de la durée d'occupation (heures, jours, mois, années...)"
why "..." ?

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Number of attendees for the event in order to add price increase"
english or french, choose your side ;)
En français s'il te plait :)

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Parameter defining if the request is for religious activities"
en français

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Area code for cities in French Polynesia"
en français

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Selected zone for pricing on private domain "
en français

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Selected zone for pricing on area managed by DAC "
en français

2022-01-24 21:58 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters_echeancier.py
> +# -*- coding: utf-8 -*-
remove file

2022-01-24 23:17 UTC, AlexisDefranoux reviewed
Vu avec masterbox

2022-02-03 19:57 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +            [duree_occupation_redevance_domaniale * 30 / 360,
Ajouter une constante nombre de jour par an et nombre de jour par mois

2022-02-03 20:55 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_3.py
> +        activite_cultuelle = personne('activite_cultuelle', period)
AIta, il s'agit bien des activité cultuelle (liée au culte). Mais en pratique, on y inclus les activités culturelle, sportives et associatives.

2022-02-03 20:58 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_8.py
> +class temporalite_redevance_domaniale_type_8(Variable):
Pour certains type (3 par exemple), la méthode est différentes.

2022-02-03 21:00 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/enums_loc.py
> +# -*- coding: utf-8 -*-
Create an Enum folder

2022-02-16 23:18 UTC, Mael-Congard-SIPF commented on openfisca_pf/base.py
> +def getVariableFromStringAndScalar(source, period, string, scalar):
@masterbox, t'es sûr que ça marche si on met un scalaire en préfixe?
J'ai du mal à généraliser la description de ce que tu avais codé xD.

2022-02-17 00:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_echeancier.py
> +# -*- coding: utf-8 -*-
OK deleted

2022-02-17 00:52 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +        tarif_spjp = parameters(period).daf.redevance_domaniale.type_calcul[nature_emprise_occupation_redevance_domaniale] == 3
OK name changed and comment added

2022-02-17 00:52 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +        condition = unite_duree_occupation_redevance_domaniale == UnitesDuree.Heures
OK modified

2022-02-17 01:00 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +        # Pour pouvoir continuer à ajouter des type de calcul, on considère que pour un type de calcul, son équivalent horaire est à +20
Comment modified:
        # Selection selon un tarif horaire ou journalier
        # Pour les tarifs du SPJP, le mode de calcul pour une même emprise change si la durée est
        # exprimée en heure et pour une durée inférieure à la journée.
        # Pour distinguer le type de calcul horaire (et sélectionner donc le bon calcul), on ajoute arbitrairement 20 au type de calcul journalier.
        # Cet ajout de 20, permet de créer des nouveaux types de calculs dans le futur.
        # L'ensemble des tarifs spéciaux du SPJP sont de type = 3

2022-02-17 01:01 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +    label = "Montant de de base la redevance domaniale dûe"
OK

2022-02-17 01:02 UTC, Mael-Congard-SIPF commented on openfisca_pf/base.py
> +def getVariableFromStringAndScalar(source, period, string, scalar):
Modifié en:
# This function aims at getting a source variable using the aggregation of a prefix and another variable
# variable = [variable 1, variable 2, variable3]
# prefix = blabla
# return [source(blablavariable1), source(blablavariable2), source(blablavariable3)]

2022-02-17 01:03 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +    label = u"Montant total de redevance domaniale de toutes les demandes du dossier"
OK

2022-02-17 01:08 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        nature_emprise_occupation_redevance_domaniale = where(type_calcul == '1', nature_emprise_occupation_redevance_domaniale.decode_to_str(), 'ip_eco_01_equipement_pays')
This part aims at set default values for the scalar "nature_emprise" when this nature is not of the same type_calcul.
The result is set to 0, in order not to have wrong values.

2022-02-17 01:14 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        montant_total = arrondiSup(montant_intermediaire * (1 - 0.8 * activite_cultuelle))
OK

2022-02-17 01:29 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +    value_type = str
@masterbox Can you check if on type_1 it is what you expected or not.

2022-02-17 01:30 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +    label = "Montant de annuel de la redevance domaniale sur les lotissements agricoles"
OK

2022-02-17 01:30 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +        zone_lot_agri = personne('zone_lot_agri', period)
OK corrected

2022-02-17 01:35 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +    label = "Montant total de la redevance domaniale dûe sur le domùaine privé"
OK

2022-02-17 01:35 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_1.py
> +        return where(type_calcul == '1', temporalite, 'Not Applicable')
OK

2022-02-17 02:35 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_23.py
> +        duree_occupation_redevance_domaniale = personne('duree_occupation_redevance_domaniale', period)
@masterbox Type_23 can only be set, if the unit is in Heures.

2022-02-17 02:35 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_3.py
> +        init = parameters(period).daf.redevance_domaniale.type_3[nature_emprise_occupation_redevance_domaniale].init
I don't remember why I did not used brackets :/

2022-02-17 02:38 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +    label = "Montant de base (journalier, annuel, mensuel) de la redevance domaniale sur le domaine privée"
OK

2022-02-17 02:38 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +        # valeur_venale = parameters(period).daf.redevance_domaniale.commune_prive[code_commune][zone_domaine_prive].valeur_venale
OK

2022-02-17 02:39 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +    label = "Montant total de la redevance domaniale dûe sur le domùaine privé"
OK

2022-02-17 02:39 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_test.py
> +# -*- coding: utf-8 -*-
OK

2022-02-17 02:46 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/enums_loc.py
> +# -*- coding: utf-8 -*-
OK

2022-02-17 02:47 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Unité de la durée d'occupation (heures, jours, mois, années...)"
Why not ? ...
Corrected xD

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Number of attendees for the event in order to add price increase"
OK

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Parameter defining if the request is for religious activities"
OK

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Area code for cities in French Polynesia"
OK

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Selected zone for pricing on private domain "
OK

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters.py
> +    label = "Selected zone for pricing on area managed by DAC "
OK

2022-02-17 02:51 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/input_parameters_echeancier.py
> +# -*- coding: utf-8 -*-
OK

2022-03-04 00:10 UTC, Mael-Congard-SIPF commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +            [duree_occupation_redevance_domaniale * 30 / 360,
Constantes ajoutées dans les paramètres.
J'ai juste laisser une constante = 1, vu que ces constantes sont le nombre de jour par blabla, ou alors je crée une constante nombre_jour_par_jour ?

2022-04-01 01:13 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_redevance_domaniale.py
> +            [duree_occupation_redevance_domaniale * 30 / 360,
Vérification des constantes ok. et ok pour ne pas créer de constante nb_jour_par_jour

2022-04-01 01:13 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_10.py
> +        for item in code_commune.decode():
On abandonne cette idée pour l'instant

2022-04-01 01:15 UTC, masterbox commented on openfisca_pf/variables/daf/redevance_domaniale/computation_type_9.py
> +        for item in code_commune.decode():
Méthode abandonnée

2022-04-01 01:15 UTC, masterbox approved these changes

2022-04-01 01:19 UTC, merged